version: "2"
services:
  motion-diffusion:
    image: motion-diffusion:latest
    build: 
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - CUDA_DEBUGGER_SOFTWARE_PREEMPTION=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/app
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]